#ifndef _REGISTERS_MAP_H_
#define _REGISTERS_MAP_H_

#ifndef FARRAY
	#define FARRAY(object, base) ((object volatile xdata *) (base))
#endif

#define g_vucxReg0 FARRAY(unsigned char, 0x000)
#define g_vucxReg1 FARRAY(unsigned char, 0x100)
#define g_vucxReg2 FARRAY(unsigned char, 0x200)
#define g_vucxReg3 FARRAY(unsigned char, 0x300)
#define g_vucxReg4 FARRAY(unsigned char, 0x400)
#define g_vucxReg5 FARRAY(unsigned char, 0x500)
#define g_vucxReg6 FARRAY(unsigned char, 0x600)
#define g_vucxReg8 FARRAY(unsigned char, 0x800)
#define g_vucxReg9 FARRAY(unsigned char, 0x900)

#define g_vucxReg FARRAY(unsigned char, 0x000)

#define REGEXT(a)	extern volatile unsigned char xdata a 
#define REGDEFEXT(a) extern volatile a##_STRUCT xdata a

REGEXT(ALERT_STATUS_1);
REGEXT(ALERT_STATUS_2);
//REGEXT(ALERT_STATUS_3);
//REGEXT(ALERT_STATUS_4);
REGEXT(CC_STATUS);
REGEXT(POWER_STATUS);
REGEXT(ALERT_MASK_LOW);
REGEXT(ALERT_MASK_HIGH);
REGEXT(ROLE_CONTROL);
REGEXT(CONFIG_STANDARD_OUTPUT);
REGEXT(TCPC_CONTROL);
REGEXT(FAULT_CONTROL);
REGEXT(POWER_CONTROL);
REGEXT(FAULT_STATUS);
REGEXT(POWER_STATUS_MASK);
REGEXT(FAULT_STATUS_MASK);
REGEXT(TRANSMIT);
REGEXT(COMMAND);
REGEXT(STANDARD_INPUT_CAPABILITIES);
REGEXT(STANDARD_OUTPUT_CAPABILITIES);
REGEXT(RECEIVE_DETECT);
REGEXT(RECEIVE_BYTE_COUNT);
REGEXT(RX_BUFF_FRAME_TYPE);
REGEXT(RECEIVED_HEADER_LOW);
REGEXT(RECEIVED_HEADER_HIGH);
REGEXT(RECEIVED_DATA_OBJECTS);
REGEXT(TRANSMIT_BYTE_COUNT);
REGEXT(TRANSMIT_HEADER_LOW);
REGEXT(TRANSMIT_HEADER_HIGH);
REGEXT(TRANSMIT_DATA_OBJECTS);
REGEXT(MESSAGE_HEADER_INFO);
REGEXT(VBUS_VOLTAGE_L);
REGEXT(VBUS_VOLTAGE_H);
REGEXT(VBUS_SINK_DISCONNECT_THRESHOLD_L);
REGEXT(VBUS_SINK_DISCONNECT_THRESHOLD_H);
REGEXT(VBUS_STOP_DISCHARGE_THRESHOLD_L);
REGEXT(VBUS_STOP_DISCHARGE_THRESHOLD_H);
REGEXT(VBUS_VOLTAGE_ALARM_HI_CFG_L);
REGEXT(VBUS_VOLTAGE_ALARM_HI_CFG_H);
REGEXT(VBUS_VOLTAGE_ALARM_LO_CFG_L);
REGEXT(VBUS_VOLTAGE_ALARM_LO_CFG_H);

REGEXT(SFT_HD_RST_EN);
REGEXT(REG_OPTION_CTR);
REGEXT(ALERT_CLR_ADDR_SET);
REGEXT(REG_OPTION_CTR_1);

REGEXT(HD_RST_SEND_RDY_TIMER_BYTE0);
REGEXT(HD_RST_SEND_RDY_TIMER_BYTE1);
REGEXT(GOODCRC_BUS_IDLE_TIMER_BYTE_0);
REGEXT(GOODCRC_BUS_IDLE_TIMER_BYTE_1);
REGEXT(TX_MSG_BUS_IDLE_TIMER_BYTE_0);
REGEXT(TX_MSG_BUS_IDLE_TIMER_BYTE_1);
REGEXT(TX_MSG_BUS_IDLE_TIMER_BYTE_2);
REGEXT(TX_RETRY_COUNTER);

REGEXT(ALERT_STATUS_3);
REGEXT(ALERT_STATUS_4);
REGEXT(ALERT_STATUS_5);

REGEXT(REG_WID_SEL);

REGEXT(FW_VER_MAJOR);
REGEXT(FW_VER_MIDDLE);
REGEXT(FW_VER_MINOR);

//REGEXT(ALERT_STATUS_COMBO_4);
//REGEXT(ALERT_STATUS_COMBO_5);
REGEXT(ALERT_MASK_REG_0);
REGEXT(ALERT_MASK_REG_1);

REGEXT(BMC_PHY_CTR0);
REGEXT(BMC_PHY_CTR1);
REGEXT(BMC_PHY_CTR2);
REGEXT(BMC_PHY_CTR3);
REGEXT(BMC_PHY_CTR4);
REGEXT(BMC_PHY_CTR5);
REGEXT(BMC_PHY_CTR6);
REGEXT(BMC_PHY_CTR7);
REGEXT(BMC_PHY_CTR8);
REGEXT(BMC_PHY_CTR9);
REGEXT(BMC_PHY_CTR10);
REGEXT(BMC_PHY_CTR11);

REGEXT(GDCRC_TIMER_BYTE0);
REGEXT(GDCRC_TIMER_BYTE1);
REGEXT(GOODCRC_RECEIVE_TIMER_BYTE0);
REGEXT(GOODCRC_RECEIVE_TIMER_BYTE1);
REGEXT(GDCRC_HEADER_BYTE_L);
REGEXT(GDCRC_HEADER_BYTE_H);
REGEXT(HD_RST_RTY_TIMER_BYTE0);
REGEXT(HD_RST_RTY_TIMER_BYTE1);
REGEXT(HD_CB_RTY_COUNT);

//REGEXT(FW_ALERT_STATUS);
REGEXT(BIST_CONT_MODE_BYTE0);
REGEXT(BIST_CONT_MODE_BYTE1);
REGEXT(BIST_CONT_MODE_BYTE2);
REGEXT(BIST_CONT_MODE_CTR);

REGEXT(REGDD);

REGEXT(REG_VENDOR_CTRL0);
REGEXT(REG_VENDOR_CTRL1);
REGEXT(REG_VENDOR_CTRL2);
REGEXT(REG_VENDOR_CTRL3);
REGEXT(REG_VENDOR_CTRL4);

REGEXT(CC_DET_IRQ_STATUS0);
REGEXT(CC_DET_IRQ_STATUS1);
REGEXT(CC_DET_DBG_SEL);
REGEXT(CC_DET_DBG_OUT);
REGEXT(REG_PHY_CTRL5);
//REGEXT(REG_VBUS_VOLTAGE_MPU);
REGEXT(REG_HPD_TOG);
REGEXT(REGHPD);
REGEXT(AOP_REG_ANATOP_7_0);
REGEXT(AOI_REG_ANATOP_15_8);
REGEXT(REG_EQTX_31_24);

REGEXT(REG_TUSB_DRV_15_8);
REGEXT(REG_RUSB_DRV_7_0);
REGEXT(REG_RUSB_DRV_15_8);
REGEXT(REG_RUSB_DRV_23_16);

REGEXT(REG_EQRX_23_16);
REGEXT(REG_EQRX_31_24);
REGEXT(CHIP_ID_L);
REGEXT(CHIP_ID_H);
REGEXT(REVISION_L);
REGEXT(REVISION_H);
REGEXT(REG_GPIO_SEL);
REGEXT(REG_GPIO_OUT);
REGEXT(REG_GPIO_OEB);
REGEXT(REG_GPIO_ODEN);
REGEXT(REG_GPIO_IVEN);
REGEXT(REG_GPIO_RD_CTL);
REGEXT(REG_GPIOP_SEL);
REGEXT(REG_GPIOP_OUT);
REGEXT(REG_GPIOP_OEB);
REGEXT(GPIO_RD_BACK);
REGEXT(OTHER_STATUS);
REGEXT(REG_IOMODE_CTL);
REGEXT(REG_STRETCH);
REGEXT(REKCKTOP_AOI);
REGEXT(PDC_REG12AOI_7_0);
REGEXT(PDC_REG12AOP_15_8);
REGEXT(AOP_REG_PDC_79_72);
REGEXT(PDC_STAT_7_0);
REGEXT(PDC_STAT_15_8);
REGEXT(PDC_STAT_23_16);
REGEXT(PDC_STAT_31_24);

REGEXT(REG_IRQ_SRC_CTL);
REGEXT(AOP_REG_PDC_63_56);
REGEXT(AOI_REG_ANATOP_31_24);
REGEXT(AOI_REG_ANATOP_39_32);
REGEXT(AOI_REG_ANATOP_47_40);

REGEXT(AOI_REG_PDC_15_8);
REGEXT(AOI_REG_ANATOP_63_56);
REGEXT(AOI_REG_PDC_23_16);
REGEXT(AOI_REG_PDC_31_24);
REGEXT(AOI_REG_PDC_39_32);
REGEXT(AOI_REG_PDC_79_72);

REGEXT(AOI_REG_PDC_95_88);

REGEXT(FUNC_IRQ_MASK);
REGEXT(FUNC_IRQ_STATUS);
REGEXT(I2C_OFFSET);
REGEXT(I2C_WRDATA);

REGEXT(CTLIRQ_CTL);
REGEXT(CTL_IRQ);
REGEXT(MPU_HOLD_MODE);
REGEXT(TO_MPU_OFFSET);
REGEXT(TO_MPU_WRDATA);
REGEXT(FROM_MPU_RDATA);
REGEXT(TESTI2CADDR);
REGEXT(ADDRCFG0);
REGEXT(ADDRCFG4);
REGEXT(MPU_CTL);
REGEXT(READSPI_ADDRL);
REGEXT(READSPI_ADDRH);
REGEXT(READSPI_ADDRE);
REGEXT(READSPI_READY);
REGEXT(READSPI_DATA);

REGEXT(MI2CSLV_ADDR);
REGEXT(MI2C_OFFSET);
REGEXT(MI2C_WDATA);
REGEXT(MI2C_RDATA);
REGEXT(MI2C_LEN);
REGEXT(MI2C_CTL);

REGEXT(CTL_DEBUG_SEL);

REGEXT(DEBUG_IN);
REGEXT(DEBUG_SEL);
REGEXT(STA_P2_75);
REGEXT(REG_MI2C_MODE);

REGEXT(PDC_REG12AOI_7_0);
REGEXT(PDC_REG12AOI_15_8);
REGEXT(PDC_REG12AOI_23_16);
REGEXT(PDC_REG12AOI_31_24);
REGEXT(PDC_REG12AOI_39_32);
REGEXT(PDC_REG12AOI_47_40);

REGEXT(TX_RX_Debug_Port_Index);
REGEXT(TX_RX_Debut_Port_Output);

REGEXT(REG_DEBOUNCE_CTRL0);
REGEXT(REG_DEBOUNCE_CTRL1);
REGEXT(REG_DEBOUNCE_CTRL2);
REGEXT(REG_DEBOUNCE_CTRL3);
REGEXT(REG_DEBOUNCE_CTRL4);
REGEXT(REG_DEBOUNCE_CTRL5);
REGEXT(REG_DEBOUNCE_CTRL6);
REGEXT(REG_DLPF_CTRL0);
REGEXT(REG_DET_CTRL0);
REGEXT(REG_DET_CTRL1);
REGEXT(REG_DET_CTRL2);
REGEXT(REG_DET_CTRL3);
REGEXT(REG_DET_CTRL4);
REGEXT(REG_DET_CTRL5);
REGEXT(REG_DET_CTRL6);

REGEXT(REG_CC_DET_INT_MASK0);
REGEXT(REG_CC_DET_INT_MASK1);
REGEXT(REG_CC_DET_INT_MASK2);
REGEXT(REG_CC_DET_INT_MASK3);
REGEXT(REG_CC_DET_INT_MASK4);
REGEXT(REG_CC_DET_INT_MASK5);

REGEXT(CC_DET_IRQ_STATUS0);
REGEXT(CC_DET_IRQ_STATUS1);
REGEXT(CC_DET_IRQ_STATUS2);
REGEXT(CC_DET_IRQ_STATUS3);
REGEXT(CC_DET_IRQ_STATUS4);
REGEXT(CC_DET_IRQ_STATUS5);

REGEXT(CC_DET_IRQ_INT0);
REGEXT(CC_DET_IRQ_INT1);
REGEXT(CC_DET_IRQ_INT2);
REGEXT(CC_DET_IRQ_INT3);
REGEXT(CC_DET_IRQ_INT4);
REGEXT(CC_DET_IRQ_INT5);

REGEXT(REG_CC1_DCC);
REGEXT(REG_CC2_DCC);
REGEXT(REG_VBUS_DCC);
REGEXT(REG_VCONN_DCC);
REGEXT(REG_TMP_VBUS_VOL_7_0);
REGEXT(REG_TMP_VBUS_VOL_15_8);
REGEXT(REG_CC_STATUS);
REGEXT(REG_POWER_STATUS);
REGEXT(FAULT_STATUS_TRIG);
REGEXT(OTHER_CTRL0);
REGEXT(REG_SET_CLR);
REGEXT(OTHER_CTRL1);

REGEXT(OTHER_CTRL3);
REGEXT(VENDOR_ID_L);
REGEXT(VENDOR_ID_H);
REGEXT(PRODUCT_ID_L);
REGEXT(PRODUCT_ID_H);
REGEXT(DEVICE_ID_L);
REGEXT(DEVICE_ID_H);
REGEXT(USBTYPEC_REV_L);
REGEXT(USBTYPEC_REV_H);
REGEXT(USBPD_REV_VER_L);
REGEXT(USBPD_REV_VER_H);
REGEXT(PD_INTERFACE_REV_L);
REGEXT(PD_INTERFACE_REV_H);
REGEXT(DEVICE_CAPABILITIES_1);
REGEXT(DEVICE_CAPABILITIES_2);
REGEXT(DEVICE_CAPABILITIES_3);
REGEXT(DEVICE_CAPABILITIES_4);

REGEXT(POWER_ON_RESET);

#endif